# Generated by Django 4.2.16 on 2025-12-05 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(default=list, help_text='List of permissions')),
                ('redirect_url', models.CharField(help_text='Dashboard URL after login', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ERP Role',
                'verbose_name_plural': 'ERP Roles',
                'db_table': 'ai_erp_role',
            },
        ),
        migrations.CreateModel(
            name='UserERPProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (6-10 years)'), ('expert', 'Expert (10+ years)'), ('consultant', 'Consultant/Specialist')], max_length=20)),
                ('primary_domain', models.CharField(choices=[('upstream', 'Upstream Operations'), ('midstream', 'Midstream Operations'), ('downstream', 'Downstream Operations'), ('offshore', 'Offshore Engineering'), ('onshore', 'Onshore Engineering'), ('process', 'Process Engineering'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical Engineering'), ('instrumentation', 'Instrumentation & Controls'), ('safety', 'Safety Engineering'), ('environmental', 'Environmental Engineering')], max_length=30)),
                ('secondary_domains', models.JSONField(default=list, help_text='Additional engineering domains')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('certifications', models.JSONField(default=list)),
                ('specializations', models.JSONField(default=list)),
                ('ip_whitelist', models.JSONField(default=list, help_text='Allowed IP addresses')),
                ('access_hours', models.JSONField(default=dict, help_text='Allowed access hours by day')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=3)),
                ('ai_assistant_enabled', models.BooleanField(default=True)),
                ('preferred_ai_model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('ai_analysis_level', models.CharField(choices=[('basic', 'Basic Analysis'), ('detailed', 'Detailed Analysis'), ('expert', 'Expert Level Analysis')], default='detailed', max_length=20)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_drawings_analyzed', models.PositiveIntegerField(default=0)),
                ('total_simulations_run', models.PositiveIntegerField(default=0)),
                ('ai_queries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='ai_erp.erprole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_profile', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'User ERP Profile',
                'verbose_name_plural': 'User ERP Profiles',
                'db_table': 'ai_erp_user_profile',
            },
        ),
        migrations.CreateModel(
            name='ProjectERPInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('exploration', 'Exploration'), ('development', 'Field Development'), ('production', 'Production'), ('maintenance', 'Maintenance & Inspection'), ('decommissioning', 'Decommissioning'), ('pipeline', 'Pipeline Project'), ('facility', 'Facility Construction'), ('refinery', 'Refinery Project'), ('offshore', 'Offshore Platform'), ('environmental', 'Environmental Project')], max_length=20)),
                ('engineering_domain', models.CharField(choices=[('upstream', 'Upstream Operations'), ('midstream', 'Midstream Operations'), ('downstream', 'Downstream Operations'), ('offshore', 'Offshore Engineering'), ('onshore', 'Onshore Engineering'), ('process', 'Process Engineering'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical Engineering'), ('instrumentation', 'Instrumentation & Controls'), ('safety', 'Safety Engineering'), ('environmental', 'Environmental Engineering')], max_length=30)),
                ('field_location', models.JSONField(default=dict, help_text='Coordinates and location details')),
                ('water_depth', models.FloatField(blank=True, help_text='Water depth in meters (for offshore)', null=True)),
                ('reservoir_type', models.CharField(blank=True, max_length=50)),
                ('fluid_type', models.CharField(blank=True, help_text='Oil, Gas, Condensate, etc.', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=10)),
                ('safety_requirements', models.JSONField(default=list)),
                ('environmental_considerations', models.JSONField(default=list)),
                ('ai_analysis_enabled', models.BooleanField(default=True)),
                ('ai_recommendations', models.JSONField(default=list)),
                ('predictive_maintenance_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_info', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project ERP Information',
                'verbose_name_plural': 'Project ERP Information',
                'db_table': 'ai_erp_project_info',
            },
        ),
        migrations.CreateModel(
            name='AISystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('drawing_analysis', 'Drawing Analysis'), ('simulation', 'Simulation'), ('recommendation', 'AI Recommendation'), ('prediction', 'Predictive Analysis'), ('anomaly', 'Anomaly Detection'), ('optimization', 'Process Optimization'), ('safety_check', 'Safety Analysis'), ('cost_estimation', 'Cost Estimation')], max_length=20)),
                ('ai_model_used', models.CharField(max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'AI System Log',
                'verbose_name_plural': 'AI System Logs',
                'db_table': 'ai_erp_system_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
