# Generated by Django 5.0.2 on 2025-12-06 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_erp', '0002_ai_user_management_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisystemlog',
            name='log_type',
            field=models.CharField(choices=[('drawing_analysis', 'Drawing Analysis'), ('simulation', 'Simulation'), ('recommendation', 'AI Recommendation'), ('prediction', 'Predictive Analysis'), ('anomaly', 'Anomaly Detection'), ('optimization', 'Process Optimization'), ('safety_check', 'Safety Analysis'), ('cost_estimation', 'Cost Estimation'), ('user_behavior_analysis', 'User Behavior Analysis'), ('system_optimization', 'System Optimization'), ('security_analysis', 'Security Analysis')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='aiinsightmodel',
            index=models.Index(fields=['insight_type', '-created_at'], name='ai_insight__insight_e80dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightmodel',
            index=models.Index(fields=['priority', '-created_at'], name='ai_insight__priorit_77fe20_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightmodel',
            index=models.Index(fields=['is_resolved'], name='ai_insight__is_reso_1f5120_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['metric_type', '-recorded_at'], name='system_metr_metric__08a8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['is_critical'], name='system_metr_is_crit_1f516c_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='user_activi_user_id_c9669f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', '-created_at'], name='user_activi_activit_30de99_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['ip_address'], name='user_activi_ip_addr_064cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessiontracking',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_6c35d9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessiontracking',
            index=models.Index(fields=['session_id'], name='user_sessio_session_c9b9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessiontracking',
            index=models.Index(fields=['-last_activity'], name='user_sessio_last_ac_c7f05c_idx'),
        ),
    ]
