# Generated by Django 5.0.2 on 2025-12-06 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_erp', '0003_alter_aisystemlog_log_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100, unique=True)),
                ('feature_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('drawing_analysis', 'Drawing Analysis'), ('document_management', 'Document Management'), ('project_management', 'Project Management'), ('simulation', 'Simulation'), ('ai_processing', 'AI Processing'), ('user_management', 'User Management'), ('system_admin', 'System Administration'), ('reporting', 'Reporting & Analytics')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Permission',
                'verbose_name_plural': 'Feature Permissions',
                'db_table': 'feature_permission',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('logout_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('features_accessed', models.JSONField(default=list)),
                ('session_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login History',
                'verbose_name_plural': 'User Login History',
                'db_table': 'user_login_history',
                'ordering': ['-login_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserS3Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_bucket_name', models.CharField(max_length=100)),
                ('s3_folder_path', models.CharField(max_length=200)),
                ('storage_quota_gb', models.FloatField(default=10.0)),
                ('current_usage_gb', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s3_storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User S3 Storage',
                'verbose_name_plural': 'User S3 Storage',
                'db_table': 'user_s3_storage',
            },
        ),
        migrations.CreateModel(
            name='UserFeatureAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read/Write'), ('admin', 'Full Admin')], default='read', max_length=20)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_erp.featurepermission')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feature Access',
                'verbose_name_plural': 'User Feature Access',
                'db_table': 'user_feature_access',
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
