# Generated by Django 4.2.16 on 2025-12-06 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_erp', '0004_featurepermission_userloginhistory_users3storage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('project_type', models.CharField(choices=[('energy-transition', 'Energy Transition'), ('industry-transformation', 'Industry Transformation'), ('future-proof-communities', 'Future-Proof Communities'), ('engineering-consulting', 'Engineering Consulting'), ('other', 'Other')], max_length=50, verbose_name='Project Type')),
                ('message', models.TextField(verbose_name='Message/Requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('auto_reply_sent', models.BooleanField(default=False)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='website', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation Request',
                'verbose_name_plural': 'Consultation Requests',
                'db_table': 'consultation_requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='consultatio_status_8fb004_idx'), models.Index(fields=['submitted_at'], name='consultatio_submitt_ac6a73_idx'), models.Index(fields=['reference_number'], name='consultatio_referen_b80726_idx'), models.Index(fields=['email'], name='consultatio_email_b39857_idx')],
            },
        ),
    ]
