# Generated by Django 6.0 on 2025-12-04 15:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIndustry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Industry',
                'verbose_name_plural': 'Service Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('service_type', models.CharField(choices=[('consulting', 'Consulting'), ('engineering', 'Engineering'), ('design', 'Design'), ('implementation', 'Implementation'), ('maintenance', 'Maintenance'), ('training', 'Training'), ('audit', 'Audit'), ('research', 'Research')], default='consulting', max_length=20)),
                ('duration_min', models.PositiveIntegerField(blank=True, help_text='Minimum duration in days', null=True)),
                ('duration_max', models.PositiveIntegerField(blank=True, help_text='Maximum duration in days', null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_unit', models.CharField(blank=True, help_text='e.g., per day, per project, per hour', max_length=50)),
                ('is_price_negotiable', models.BooleanField(default=True)),
                ('requirements', models.TextField(blank=True, help_text='Client requirements')),
                ('deliverables', models.TextField(blank=True, help_text='Service deliverables')),
                ('methodology', models.TextField(blank=True, help_text='Service methodology')),
                ('required_expertise', models.CharField(blank=True, max_length=200)),
                ('team_size_min', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size_max', models.PositiveIntegerField(blank=True, null=True)),
                ('featured_image', models.URLField(blank=True)),
                ('banner_image', models.URLField(blank=True)),
                ('brochure_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Benefit',
                'verbose_name_plural': 'Service Benefits',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('is_key_feature', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIndustryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.PositiveIntegerField(default=5, help_text='Relevance score from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='services.serviceindustry')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_mappings', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Industry Mapping',
                'verbose_name_plural': 'Service Industry Mappings',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('client_title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='new', max_length=20)),
                ('response_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, help_text='e.g., 2-3 days, 1 week', max_length=100)),
                ('deliverable', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Process',
                'verbose_name_plural': 'Service Processes',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('client_title', models.CharField(blank=True, max_length=200)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('client_photo', models.URLField(blank=True)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_duration', models.CharField(blank=True, max_length=100)),
                ('project_value', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Testimonial',
                'verbose_name_plural': 'Service Testimonials',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_published'], name='services_se_categor_7809a3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_featured'], name='services_se_service_8cda79_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['popularity_score', 'views_count'], name='services_se_popular_c549b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceindustrymapping',
            unique_together={('service', 'industry')},
        ),
        migrations.AddIndex(
            model_name='serviceinquiry',
            index=models.Index(fields=['status', 'urgency'], name='services_se_status_64f510_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinquiry',
            index=models.Index(fields=['assigned_to', 'status'], name='services_se_assigne_0cb9bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprocess',
            unique_together={('service', 'step_number')},
        ),
    ]
