# Generated by Django 4.2.16 on 2025-12-05 05:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('drawing_number', models.CharField(max_length=100, unique=True)),
                ('revision', models.CharField(default='A', max_length=10)),
                ('drawing_type', models.CharField(choices=[('pid', 'Piping & Instrumentation Diagram'), ('pfd', 'Process Flow Diagram'), ('ga', 'General Arrangement'), ('isometric', 'Isometric Drawing'), ('plan', 'Plan View'), ('section', 'Section View'), ('detail', 'Detail Drawing'), ('schematic', 'Schematic Diagram'), ('electrical', 'Electrical Drawing'), ('mechanical', 'Mechanical Drawing'), ('structural', 'Structural Drawing'), ('hvac', 'HVAC Drawing'), ('firewater', 'Fire & Safety Systems'), ('layout', 'Equipment Layout'), ('plot_plan', 'Plot Plan')], max_length=20)),
                ('file', models.FileField(upload_to='drawings/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'tiff', 'dwg', 'dxf'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scale', models.CharField(blank=True, max_length=50)),
                ('units', models.CharField(default='mm', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_drawings', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'Drawing Document',
                'verbose_name_plural': 'Drawing Documents',
                'db_table': 'drawing_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('general', 'General Comment'), ('revision', 'Revision Request'), ('approval', 'Approval Note'), ('concern', 'Safety Concern'), ('suggestion', 'Improvement Suggestion'), ('compliance', 'Compliance Note'), ('ai_finding', 'AI Generated Finding')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('coordinates', models.JSONField(default=dict, help_text='X, Y coordinates on drawing')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_comments', to='authentication.rejlersuser')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drawing_analysis.drawingdocument')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'Drawing Comment',
                'verbose_name_plural': 'Drawing Comments',
                'db_table': 'drawing_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDrawingAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('text_extraction', 'Text Extraction'), ('component_detection', 'Component Detection'), ('dimension_analysis', 'Dimension Analysis'), ('symbol_recognition', 'Symbol Recognition'), ('compliance_check', 'Compliance Check'), ('safety_analysis', 'Safety Analysis'), ('cost_estimation', 'Cost Estimation'), ('material_takeoff', 'Material Take-off'), ('clash_detection', 'Clash Detection'), ('quality_check', 'Quality Check')], max_length=30)),
                ('ai_model_used', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('tokens_consumed', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('extracted_text', models.TextField(blank=True)),
                ('detected_components', models.JSONField(default=list)),
                ('identified_symbols', models.JSONField(default=list)),
                ('dimensions', models.JSONField(default=list)),
                ('materials_list', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('completeness_score', models.FloatField(blank=True, null=True)),
                ('findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('safety_concerns', models.JSONField(default=list)),
                ('compliance_issues', models.JSONField(default=list)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='drawing_analysis.drawingdocument')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_analyses', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'AI Drawing Analysis',
                'verbose_name_plural': 'AI Drawing Analyses',
                'db_table': 'ai_drawing_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=10)),
                ('changes_made', models.TextField()),
                ('file', models.FileField(upload_to='drawing_versions/%Y/%m/')),
                ('requires_approval', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to='authentication.rejlersuser')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drawing_analysis.drawingdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_versions', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'Drawing Version',
                'verbose_name_plural': 'Drawing Versions',
                'db_table': 'drawing_version',
                'ordering': ['-created_at'],
                'unique_together': {('drawing', 'version_number')},
            },
        ),
    ]
