# Generated by Django 4.2.16 on 2025-12-05 05:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('authentication', '0001_initial'),
        ('drawing_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('simulation_type', models.CharField(choices=[('cfd', 'Computational Fluid Dynamics'), ('fea', 'Finite Element Analysis'), ('thermal', 'Thermal Analysis'), ('stress', 'Stress Analysis'), ('flow', 'Flow Simulation'), ('pressure', 'Pressure Analysis'), ('vibration', 'Vibration Analysis'), ('fatigue', 'Fatigue Analysis'), ('corrosion', 'Corrosion Modeling'), ('reservoir', 'Reservoir Simulation'), ('wellbore', 'Wellbore Analysis'), ('pipeline', 'Pipeline Simulation'), ('safety', 'Safety Analysis'), ('environmental', 'Environmental Impact'), ('optimization', 'Process Optimization')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('software_used', models.CharField(help_text='Simulation software/tool', max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('license_required', models.CharField(blank=True, max_length=100)),
                ('estimated_runtime', models.DurationField(help_text='Expected simulation runtime')),
                ('cpu_hours_estimated', models.FloatField(help_text='Estimated CPU hours')),
                ('memory_required_gb', models.PositiveIntegerField(help_text='Required memory in GB')),
                ('storage_required_gb', models.PositiveIntegerField(help_text='Required storage in GB')),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='setup', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('planned_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('planned_completion', models.DateTimeField()),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('ai_recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_simulations', to='authentication.rejlersuser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_simulations', to='authentication.rejlersuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Simulation Project',
                'verbose_name_plural': 'Simulation Projects',
                'db_table': 'simulation_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_number', models.PositiveIntegerField()),
                ('parameters', models.JSONField(default=dict, help_text='Simulation parameters')),
                ('boundary_conditions', models.JSONField(default=dict)),
                ('material_properties', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cpu_time_used', models.FloatField(blank=True, help_text='CPU hours used', null=True)),
                ('memory_used_gb', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='setup', max_length=20)),
                ('convergence_achieved', models.BooleanField(blank=True, null=True)),
                ('iterations_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('results_file', models.FileField(blank=True, upload_to='simulation_results/%Y/%m/')),
                ('log_file', models.FileField(blank=True, upload_to='simulation_logs/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('warnings', models.JSONField(default=list)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulation_management.simulationproject')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_runs', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'Simulation Run',
                'verbose_name_plural': 'Simulation Runs',
                'db_table': 'simulation_run',
                'ordering': ['-started_at'],
                'unique_together': {('simulation', 'run_number')},
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('stress', 'Stress Results'), ('displacement', 'Displacement Results'), ('temperature', 'Temperature Results'), ('pressure', 'Pressure Results'), ('velocity', 'Velocity Results'), ('flow_rate', 'Flow Rate Results'), ('safety_factor', 'Safety Factor'), ('fatigue_life', 'Fatigue Life'), ('frequency', 'Frequency Analysis'), ('buckling', 'Buckling Analysis')], max_length=20)),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('average_value', models.FloatField()),
                ('units', models.CharField(max_length=50)),
                ('max_location', models.JSONField(default=dict, help_text='Coordinates of maximum value')),
                ('min_location', models.JSONField(default=dict, help_text='Coordinates of minimum value')),
                ('within_limits', models.BooleanField(blank=True, null=True)),
                ('safety_margin', models.FloatField(blank=True, null=True)),
                ('design_criteria', models.JSONField(default=dict)),
                ('ai_analysis', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(default=list)),
                ('risk_assessment', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation_management.simulationrun')),
            ],
            options={
                'verbose_name': 'Simulation Result',
                'verbose_name_plural': 'Simulation Results',
                'db_table': 'simulation_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('cad', 'CAD Model'), ('mesh', 'Mesh Model'), ('geometry', 'Geometry File'), ('input', 'Input File'), ('boundary', 'Boundary Conditions'), ('material', 'Material Properties'), ('loads', 'Load Definition'), ('constraints', 'Constraints')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='simulation_models/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['step', 'iges', 'dwg', 'dxf', 'stl', 'obj', 'inp', 'msh', 'dat'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('units', models.CharField(default='mm', max_length=20)),
                ('scale_factor', models.FloatField(default=1.0)),
                ('coordinate_system', models.CharField(default='cartesian', max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('processing_log', models.TextField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='simulation_management.simulationproject')),
                ('source_drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_models', to='drawing_analysis.drawingdocument')),
            ],
            options={
                'verbose_name': 'Simulation Model',
                'verbose_name_plural': 'Simulation Models',
                'db_table': 'simulation_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISimulationAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistance_type', models.CharField(choices=[('parameter_optimization', 'Parameter Optimization'), ('mesh_recommendations', 'Mesh Recommendations'), ('boundary_conditions', 'Boundary Conditions Setup'), ('material_selection', 'Material Selection'), ('convergence_help', 'Convergence Assistance'), ('result_interpretation', 'Result Interpretation'), ('design_optimization', 'Design Optimization'), ('failure_analysis', 'Failure Analysis')], max_length=30)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('ai_model_used', models.CharField(max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('context_data', models.JSONField(default=dict)),
                ('recommendations_applied', models.BooleanField(default=False)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistance', to='simulation_management.simulationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_ai_sessions', to='authentication.rejlersuser')),
            ],
            options={
                'verbose_name': 'AI Simulation Assistant',
                'verbose_name_plural': 'AI Simulation Assistant Sessions',
                'db_table': 'ai_simulation_assistant',
                'ordering': ['-created_at'],
            },
        ),
    ]
